### ISSUE TITLE
bgoldd crashes at block 220047

### ISSUE THREAD

**Issue by BadPirate** [trezor-graveyard/bitcoin-gold#2]
### Describe the issue
On ubuntu 16.04, clean install, when I run 'bgold-d -daemon' it gets to block 220047 and then crashes, and when I restart it replays from around 117xxx a while and then crashes again (when it hits 220047).

### Can you reliably reproduce the issue?
4/4 -- Trying again

#### If so, please list the steps to reproduce below:
1. bgoldd -daemon
2. bgold-cli getblockcount (success)
3. Wait
4. bgold-cli getblockcount (fails RPC)
5. tail debug.log -- ...
`018-02-01 17:32:45 UpdateTip: new best=000000000000041ee7a61acb03fd006d4cc7cd5c300e7e4f175827932277ba6d height=220047 version=0x00000001 log2_work=69.377534 tx=12352519 date='2013-02-07 12:01:52' progress=0.042240 cache=505.7MiB(3869523txo)`

### Expected behaviour
Some sort of log, or error, or better yet, no crash at all.

### Actual behaviour
crash

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by prusnak** [comment]
Bitcoin Gold repository is here: https://github.com/BTCGPU/BTCGPU -- report the issue there.
